/**
 * "Sign in" — which here means: choose whose shopping history to look at.
 *
 * There is no authentication in this project and this dialog does not pretend
 * otherwise; the copy says so on screen. Picking a shopper swaps the session
 * id, which is also the user id (ADR-005), so the profile, the predicted
 * segment and the coupon all change to that shopper's real computed values.
 *
 * Every shopper listed is generated by `backend/scripts/seed.py`. The endpoint
 * behind this can only return seeded rows, so no real account is reachable
 * from here.
 *
 * The segment is deliberately not shown in the list. Labelling a card "Deal
 * seeker" would give away the answer the model exists to produce.
 */

import { motion, useReducedMotion } from "framer-motion";
import { LogIn, RefreshCw, UserRound } from "lucide-react";
import { useQueryClient } from "@tanstack/react-query";
import { useState } from "react";

import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useDemoShoppers } from "@/hooks/useProfile";
import { EASE_OUT, listChild, listParent } from "@/lib/motion";
import { adoptSession, resetSession, sessionId } from "@/services/client";

export function SignInDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}) {
  const reduced = useReducedMotion();
  const queryClient = useQueryClient();
  const { data, isLoading } = useDemoShoppers(open);
  const [current, setCurrent] = useState<string>(() => sessionId());

  /** Swap identity, then drop every cached answer that belonged to the old one. */
  function switchTo(id: string) {
    adoptSession(id);
    setCurrent(id);
    queryClient.clear();
    onOpenChange(false);
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-lg">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <LogIn className="size-4 text-primary" /> Choose a shopper
          </DialogTitle>
          <DialogDescription>
            This demo has no accounts or passwords. Picking a shopper loads their real
            interaction history so you can see how the personalisation differs per customer.
          </DialogDescription>
        </DialogHeader>

        {isLoading && <p className="py-6 text-sm text-muted-foreground">Loading shoppers…</p>}

        {data && (
          <>
            <motion.div
              variants={listParent(data.shoppers.length)}
              initial={reduced ? false : "hidden"}
              animate="visible"
              className="max-h-[320px] space-y-2 overflow-y-auto pr-1"
            >
              {data.shoppers.map((shopper) => {
                const active = shopper.user_id === current;
                return (
                  <motion.button
                    key={shopper.user_id}
                    variants={listChild}
                    type="button"
                    onClick={() => switchTo(shopper.user_id)}
                    whileHover={reduced ? undefined : { x: 3 }}
                    transition={{ duration: 0.18, ease: EASE_OUT }}
                    className={
                      "flex w-full items-center gap-3 rounded-xl border p-3 text-left transition-colors " +
                      (active
                        ? "border-primary bg-primary-soft"
                        : "border-border bg-card hover:border-primary/40")
                    }
                  >
                    <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-secondary text-muted-foreground">
                      <UserRound className="size-4" />
                    </span>
                    <span className="min-w-0 flex-1">
                      <span className="block text-sm font-medium text-foreground">
                        {shopper.label}
                      </span>
                      <span className="block text-xs text-muted-foreground">
                        {shopper.events} interactions
                        {shopper.interests.length > 0 && ` · ${shopper.interests.join(", ")}`}
                      </span>
                    </span>
                    {active && <Badge variant="accent">Current</Badge>}
                  </motion.button>
                );
              })}
            </motion.div>

            <div className="flex items-center justify-between gap-3 border-t border-border pt-3">
              <p className="text-[11px] text-muted-foreground">
                Generated shoppers, not real people.
              </p>
              <Button
                variant="outline"
                size="sm"
                onClick={() => switchTo(resetSession())}
                className="gap-1.5"
              >
                <RefreshCw className="size-3.5" /> Start fresh
              </Button>
            </div>
          </>
        )}
      </DialogContent>
    </Dialog>
  );
}
