"""Train the shopper-segment classifier.

    python ml/personalization/train.py

Reads every user's interaction history, builds one feature vector per user
(app/ml/features.py -- the same code that runs at serving time), and fits a
model to recover the shopper segment from behaviour alone.

WHAT THIS DOES AND DOES NOT SHOW
--------------------------------
The segment labels are generated by backend/scripts/seed.py, so this measures
whether the pipeline can recover structure we ourselves put into the data. That
is a real and useful thing to measure -- it catches feature bugs, leakage and
train/serve skew -- but it is NOT evidence about how real shoppers behave, and
the accuracy printed here must never be quoted as if it were.

The honest claim is: "given behavioural data with segment structure in it, this
pipeline recovers the segment at X% on users it has never seen."
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "backend"))

import joblib  # noqa: E402
import numpy as np  # noqa: E402
from app.db.database import SessionLocal  # noqa: E402
from app.ml.features import FEATURE_NAMES, build_features  # noqa: E402
from app.ml.segments import SEGMENT_NAMES  # noqa: E402
from app.models.user import UserPreference  # noqa: E402
from sklearn.dummy import DummyClassifier  # noqa: E402
from sklearn.ensemble import RandomForestClassifier  # noqa: E402
from sklearn.linear_model import LogisticRegression  # noqa: E402
from sklearn.metrics import (  # noqa: E402
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
)
from sklearn.model_selection import cross_val_score, train_test_split  # noqa: E402
from sklearn.pipeline import Pipeline  # noqa: E402
from sklearn.preprocessing import StandardScaler  # noqa: E402

OUT_DIR = Path(__file__).resolve().parent / "model"
MODEL_PATH = OUT_DIR / "segment_classifier.joblib"
REPORT_PATH = OUT_DIR / "training_report.json"
RANDOM_STATE = 42
# Below this a user's history is too thin to characterise them; including them
# adds label noise that flatters nothing and teaches nothing.
MIN_EVENTS = 10


def load_dataset():
    with SessionLocal() as db:
        labels = {
            row.user_id: row.segment
            for row in db.execute(
                # `segment` is ground truth for synthetic users only.
                __import__("sqlalchemy").select(
                    UserPreference.user_id, UserPreference.segment
                )
            )
            if row.segment
        }
        features = build_features(db, list(labels))

    rows = [f for f in features if f.n_events >= MIN_EVENTS and labels.get(f.user_id)]
    if not rows:
        raise SystemExit(
            "No labelled users with enough history.\n"
            "Seed them first:  python backend/scripts/seed.py --interactions 15000"
        )

    X = np.array([r.values for r in rows], dtype=float)
    y = np.array([labels[r.user_id] for r in rows])
    return X, y


def main() -> int:
    X, y = load_dataset()
    print(f"users: {len(y)}   features: {X.shape[1]}")
    # str() because numpy hands back np.str_, whose repr leaks into the report.
    counts = {str(name): int((y == name).sum()) for name in sorted(set(y))}
    print(f"classes: {counts}")

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.25, random_state=RANDOM_STATE, stratify=y
    )

    candidates = {
        "random_forest": RandomForestClassifier(
            n_estimators=300, min_samples_leaf=2,
            random_state=RANDOM_STATE, class_weight="balanced",
        ),
        "logistic_regression": Pipeline([
            ("scale", StandardScaler()),
            ("clf", LogisticRegression(max_iter=2000, random_state=RANDOM_STATE)),
        ]),
    }

    # A stratified guesser is the floor. Without it, "we got 82%" is unreadable:
    # on four balanced classes chance is 25%, but that is only true because the
    # classes happen to be balanced, so measure it rather than assume it.
    baseline = DummyClassifier(strategy="stratified", random_state=RANDOM_STATE)
    baseline.fit(X_train, y_train)
    baseline_acc = accuracy_score(y_test, baseline.predict(X_test))

    scored = {}
    for name, model in candidates.items():
        cv = cross_val_score(model, X_train, y_train, cv=5, scoring="f1_macro")
        scored[name] = float(cv.mean())
        print(f"  {name:20} cv f1_macro = {cv.mean():.3f} (+/- {cv.std():.3f})")

    best_name = max(scored, key=scored.get)
    model = candidates[best_name]
    model.fit(X_train, y_train)
    predicted = model.predict(X_test)

    accuracy = accuracy_score(y_test, predicted)
    macro_f1 = f1_score(y_test, predicted, average="macro")
    labels_sorted = sorted(set(y))

    print()
    print(f"chosen: {best_name}")
    print(f"  holdout accuracy  {accuracy:.3f}   (stratified guess {baseline_acc:.3f})")
    print(f"  holdout macro F1  {macro_f1:.3f}")
    print()
    print(classification_report(y_test, predicted, zero_division=0))
    print("confusion matrix (rows = true, cols = predicted)")
    print("  " + "  ".join(f"{n[:9]:>9}" for n in labels_sorted))
    for name, row in zip(labels_sorted, confusion_matrix(y_test, predicted, labels=labels_sorted), strict=True):
        print(f"{name[:16]:16} " + "  ".join(f"{v:>9}" for v in row))

    importances = None
    if hasattr(model, "feature_importances_"):
        pairs = sorted(
            zip(FEATURE_NAMES, model.feature_importances_, strict=True),
            key=lambda kv: kv[1], reverse=True,
        )
        importances = [{"feature": f, "importance": round(float(v), 4)} for f, v in pairs]
        print()
        print("what the model actually keys on:")
        for feature, value in pairs[:10]:
            print(f"  {feature:24} {value:.4f}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(
        {
            "model": model,
            "feature_names": list(FEATURE_NAMES),
            "classes": list(model.classes_),
            "min_events": MIN_EVENTS,
        },
        MODEL_PATH,
    )
    REPORT_PATH.write_text(
        json.dumps(
            {
                "chosen_model": best_name,
                "n_users": len(y),
                "n_features": X.shape[1],
                "class_counts": counts,
                "cv_f1_macro": scored,
                "holdout_accuracy": round(float(accuracy), 4),
                "holdout_macro_f1": round(float(macro_f1), 4),
                "stratified_baseline_accuracy": round(float(baseline_acc), 4),
                "confusion_matrix": {
                    "labels": labels_sorted,
                    "rows_true_cols_predicted":
                        confusion_matrix(y_test, predicted, labels=labels_sorted).tolist(),
                },
                "feature_importances": importances,
                "caveat": (
                    "Segment labels are generated by backend/scripts/seed.py. "
                    "These figures show the pipeline recovers structure that was "
                    "put into the data; they are not evidence about real shopper "
                    "behaviour."
                ),
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    print()
    print(f"saved model  -> {MODEL_PATH.relative_to(REPO)}")
    print(f"saved report -> {REPORT_PATH.relative_to(REPO)}")

    unknown = set(y) - set(SEGMENT_NAMES)
    if unknown:
        print(f"\nWARNING: no offer policy defined for segments {sorted(unknown)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
